# Empty Template for private repos: https://gitpod.new/
image: gitpod/workspace-full

tasks:
  - name: Setup
    # init: |
    #   sudo apt-get update
    #   sudo apt-get install -y \
    #     tilix \
    #     openbox \
    #     xrdp \
    #     fonts-liberation \
    #     libasound2 \
    #     libnspr4 \
    #     libnss3 \
    #     xdg-utils \
    #     libgconf-2-4 \
    #     wget
    #   sudo mkdir -p /home/gitpod/Downloads
    #   wget -P /home/gitpod/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #   sudo dpkg -i /home/gitpod/Downloads/google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
    #   rm -rf /home/gitpod/Downloads
    command: echo "Hello World"

vscode:
  extensions:
    - ms-vscode-remote.remote-containers

# Optional: Add Tailscale configuration if supported
# For now, you need to manually handle Tailscale setup in GitPod
