# Empty Template for private repos: https://gitpod.new/
# image: gitpod/workspace-full
image: mcr.microsoft.com/devcontainers/base:ubuntu

tasks:
  - name: tailscale-install
    command: |
      /bin/bash ./ghrc.io/tailscale.sh
  - name: tailscale-entrypoint
    command: |
      /bin/bash ./ghrc.io/tailscale.sh
  - name: Setup
    init: |
      echo "gitpod:gitpod" | sudo chpasswd
      /bin/bash .devcontainer/setup.sh
    command: sudo tailscale up

vscode:
  extensions:
    - ms-vscode-remote.remote-containers

# Optional: Add Tailscale configuration if supported
# For now, you need to manually handle Tailscale setup in GitPod
