# Empty Template for private repos: https://gitpod.new/
image:
  file: Dockerfile.openbox-chrome

tasks:
  - name: Setup
    command: /bin/bash .devcontainer/setup.sh

vscode:
  extensions:
    - ms-vscode-remote.remote-containers

# Optional: Add Tailscale configuration if supported
# For now, you need to manually handle Tailscale setup in GitPod
