# Empty Template for private repos: https://gitpod.new/
image: ubuntu:latest

tasks:
  - name: Build
    init: |
      sudo apt update && sudo apt install -y git wget
  - name: Setup
    command: /bin/bash .devcontainer/setup.sh

vscode:
  extensions:
    - ms-vscode-remote.remote-containers

# Optional: Add Tailscale configuration if supported
# For now, you need to manually handle Tailscale setup in GitPod
