# Empty Template for private repos: https://gitpod.new/
# image: gitpod/workspace-full
image: mcr.microsoft.com/devcontainers/base:ubuntu

tasks:
  # command: has logic to restore the tailscale state from gitpod user's env vars
  - name: tailscaled
    command: |
        if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
          sudo mkdir -p /var/lib/tailscale 
          echo "${TAILSCALE_STATE_MYPROJECT}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
        fi
        sudo tailscaled
  - name: tailscale
    command: |
        if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
          sudo -E tailscale up
        else
          sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
          # store the tailscale state into gitpod user
          gp env TAILSCALE_STATE_MYPROJECT="$(sudo cat /var/lib/tailscale/tailscaled.state)"
        fi
  - name: Setup
    init: |
      echo "gitpod:gitpod" | sudo chpasswd
      /bin/bash .devcontainer/setup.sh
    command: echo "Hello World"

vscode:
  extensions:
    - ms-vscode-remote.remote-containers

# Optional: Add Tailscale configuration if supported
# For now, you need to manually handle Tailscale setup in GitPod
